export default {
    "hp": "hp",
    "hp%": "hp_",
    "base_hp": "base_hp",
    "atk": "atk",
    "atk%": "atk_",
    "atkspd%": "atkSPD_",
    "base_atk": "base_atk",
    "def": "def",
    "def%": "def_",
    "em": "eleMas",
    "er": "enerRech_",
    "cr": "critRate_",
    "cd": "critDMG_",
    "phys%": "physical_dmg_",
    "anemo%": "anemo_dmg_",
    "geo%": "geo_dmg_",
    "electro%": "electro_dmg_",
    "hydro%": "hydro_dmg_",
    "pyro%": "pyro_dmg_",
    "cryo%": "cryo_dmg_",
    "dendro%": "dendro_dmg_",
    "heal": "heal_",
    "dmg%": "all_dmg_",
    // Reaction-specific damage bonuses (percentage)
    "bloom%": "bloom_dmg_",
    "burgeon%": "burgeon_dmg_",
    "hyperbloom%": "hyperbloom_dmg_",
    "lunarbloom%": "lunarbloom_dmg_",
    "lunarcharged%": "lunarcharged_dmg_",
    // Reaction-specific flat damage increase
    "bloom_flat": "bloom_dmgInc",
    "burgeon_flat": "burgeon_dmgInc",
    "hyperbloom_flat": "hyperbloom_dmgInc",
    "lunarbloom_flat": "lunarbloom_dmgInc",
    "lunarcharged_flat": "lunarcharged_dmgInc",
} as Record<string, string>;
